dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - git
      - doxygen
      - graphviz
script:
- export CC=gcc-7
- export CXX=g++-7
# Check versions of gcc, g++ and cmake
 - gcc -v && g++ -v && cmake --version

- "MYHOME=`pwd`"
- sudo mkdir /usr/src/googletest
- sudo git clone "https://github.com/google/googletest.git" /usr/src/googletest

- cd /usr/src/googletest/googletest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo mkdir -p /usr/include/gtest
- sudo cp  -rp  /usr/src/googletest/googletest/include/* /usr/include/

- cd /usr/src/googletest/googlemock
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo mkdir -p /usr/include/gmock
- sudo cp  -rp  /usr/src/googletest/googlemock/include/* /usr/include/

- cd "${MYHOME}"
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
 - provider: script
   skip_cleanup: true
   script:
   - curl -T draw-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usrgmatveev:$BINTRAY_API_KEY "https://api.bintray.com/content/srgmatveev/otus-cpp/draw/$TRAVIS_BUILD_NUMBER/draw-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 - provider: pages
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   keep-history: true
   local_dir: ./build/docs/html
   on:
    branch: master
